### PR TITLE
Fixed bug with keyboard

### LINKED ISSUE #18: [Bug] Opening keyboard after changing rotation
After canceling adding new task (tap on adding new task -> tap on editText OR tap on adding new task again without entering title -> close adding menu by swipe down) and changing rotation, keyboard opening.

### PR DESCRIPTION
**Pull request by achatina**
### Description
Fixes keyboard opening on screen rotation. Fixes #18

### CODE REVIEW

File: app/src/main/java/io/github/dmi3coder/scorsero/score/ScoreStarterController.kt [hunk 1]
```diff
@@ -41,6 +40,7 @@ class ScoreStarterController() : Controller(), ScoreCreationContract.View, OnCli
 
       override fun onStateChanged(bottomSheet: View, newState: Int) {
         if (newState == BottomSheetBehavior.STATE_HIDDEN) {
+          view!!.title_field.clearFocus()
```
Comment (dmi3coder) [inline app/src/main/java/io/github/dmi3coder/scorsero/score/ScoreStarterController.kt]: It is possible that `view` will be null in this situation, use `bottomSheet` instead

Comment (dmi3coder) [inline app/src/main/java/io/github/dmi3coder/scorsero/score/ScoreStarterController.kt]: Also `bottomSheet` will be non-null so !! operator is not required
